# Generated by Django 4.0.1 on 2022-01-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Remarks',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
