# Generated by Django 4.0.1 on 2022-01-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_document_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Remarks',
            field=models.TextField(null=True),
        ),
    ]
